apiVersion: apps/v1
kind: Deployment
metadata:
  name: luna-deployment
  labels:
    app: luna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luna
  template:
    metadata:
      labels:
        app: luna
    spec:
      containers:
      - name: luna
        image: sisisin/gke-node:20220924-002231
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: luna-cluster-service
spec:
  type: ClusterIP
  selector:
    app: luna
  ports:
    - port: 8080
      targetPort: 80
