name: preview infra/main
on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/main/**/*'
jobs:
  pulumi_preview:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    name: run pulumi preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-infra

      - name: Preview infrastructure update
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: ./infra/main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
